### ISSUE TITLE
what this "so I delete the mechanism of extend final logists, just use their mechanism of deocode from article and vocab" mean? 

### ISSUE THREAD

**Issue by alphanlp** [policeme/transformer-pointer-generator#14]

**Comment by xiongma** [comment]
if u see the seq2seq genertor pointer, you can see, the author extend the final decoder logists,  the extend part is vocab which can not find in vocab, because of I use this in transformer, I got NAN, when I train this model, and another reason is I use word piece, I think the vocab contain all of chinese word piece, it unnecssary, so I didn't extend the final decoder logists

**Comment by alphanlp** [comment]
thanks for you answer
