### ISSUE TITLE
How about the performance?

### ISSUE THREAD

**Issue by maozezhong** [policeme/transformer-pointer-generator#23]
Hello, Have you test the model?  How about the performance of the model ?

**Comment by maozezhong** [comment]
@policeme Or do you have some sample prediction?  Hope for your reply

**Comment by xiongma** [comment]
when I trained this model, I had some sample predictions, but this project had pass long ago, I deleted this samples, recent days, my work is so busy, I don't have time to finish it, if I finish my work, I will compelet it. otherwise, if u really want this sampes, you can train it by youself. thx


Cally Ma (马雄)
Chongqing University of Post and Telecommunications
Mobile: +86 15025700935
E-mail: mx15025700935@aliyun.com




------------------------------------------------------------------
发件人：maozezhong <notifications@github.com>
发送时间：2019年9月18日(星期三) 11:51
收件人：policeme/transformer-pointer-generator <transformer-pointer-generator@noreply.github.com>
抄　送：Cally <mx15025700935@aliyun.com>; Mention <mention@noreply.github.com>
主　题：Re: [policeme/transformer-pointer-generator] How about the performance? (#23)

@policeme Or do you have some sample prediction? Hope for your reply
