### ISSUE TITLE
Add coverage mechanism

### ISSUE THREAD

**Issue by yjyGo** [policeme/transformer-pointer-generator#5]
if I want to add a coverage mechanism, which part code should I modify? Can you give me some advice? Because I do not ever research abstract summarization yet.

**Comment by xiongma** [comment]
if you want to add coverage mechanism to this model, your summary must be long, because coverage mechanism doesn't suit short summary, this is my advices:
1. [https://github.com/policeme/transformer-pointer-generator/blob/0456c6e3aec58e33a0ec497879e697117c122d55/modules.py#L85](vanilla_attention    softmax) in this line, you should add coverage mechanism.
2. change the the way of calculate loss, you can see more details in pointer-generator paper.

**Comment by xiongma** [comment]
if you want to implement it, you can see more details in paper, when I do this work, I found some information about coverage mechanism, but all of this information said it doesn't suit for short summary, so I given up, if you try this, and have a good result, hope you can tell me.

**Comment by yjyGo** [comment]
ok, thank you!
